import React from 'react';
import { Book } from 'lucide-react';

export default function SilentPaymentsGlossarySlide() {
    const terms = [
        {
            term: "BIP (Bitcoin Improvement Proposal)",
            definition: "A design document for introducing features or information to Bitcoin."
        },
        {
            term: "BIP 352",
            definition: "The Bitcoin Improvement Proposal for Silent Payments, aiming to improve transaction privacy."
        },
        {
            term: "Fungibility",
            definition: "In the context of Bitcoin, fungibility refers to the property where each unit of BTC is interchangeable and indistinguishable from any other unit. Enhanced privacy features like Silent Payments aim to improve Bitcoin's fungibility by making transaction histories less traceable."
        },
        {
            term: "Scan Key",
            definition: "A private key used by the recipient to detect incoming Silent Payments on the blockchain."
        },
        {
            term: "Spend Key",
            definition: "A private key used by the recipient to derive the private keys needed to spend funds received through Silent Payments."
        },
        {
            term: "Output Key",
            definition: "A public key derived from the recipient's scan and spend keys, used to create the stealth address for a Silent Payment."
        },
        {
            term: "Ephemeral Key",
            definition: "A temporary public key generated by the sender for each Silent Payment, used in creating unique outputs."
        },
        {
            term: "Tagged Hash",
            definition: "A specialized hash function used in Silent Payments for deriving shared secrets, helping to ensure the uniqueness and security of the protocol."
        },
        {
            term: "Tweak Value",
            definition: "A value derived from transaction data, used in key derivation to create unique addresses in Silent Payments."
        },
        {
            term: "Stealth Address",
            definition: "A one-time use address generated for each Silent Payment transaction to enhance privacy."
        },
        {
            term: "Public Key",
            definition: "A cryptographic key that can be shared publicly and is used to verify digital signatures or encrypt messages in the Silent Payments process."
        },
        {
            term: "Private Key",
            definition: "A secret key used to create digital signatures and derive corresponding public keys in the Silent Payments protocol."
        },
        {
            term: "Output",
            definition: "In Bitcoin transactions, including Silent Payments, an output specifies where and how much BTC is sent."
        }
    ];

    return (
        <div className="bg-white p-6 rounded-lg shadow-lg max-w-4xl mx-auto">
            <h1 className="text-3xl font-bold mb-4 text-center text-green-600">Silent Payments: Glossary of Terms</h1>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {terms.map((item, index) => (
                    <div key={index} className="bg-gray-100 p-4 rounded-lg">
                        <h2 className="text-lg font-semibold mb-2 flex items-center">
                            <Book className="text-blue-500 mr-2" size={20} />
                            {item.term}
                        </h2>
                        <p className="text-sm text-gray-700">{item.definition}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}